[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "netlify/functions/templates"

[build.environment]
  # 指定默认首页
  NETLIFY_INDEX_FILE = "platform.html"
  PYTHON_VERSION = "3.12"

[functions]
  app = { path = "netlify/functions/app.py", handler = "handler" }
  test = { path = "netlify/functions/test_function.py", handler = "handler" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200